name: "Php 8.0"

on:
  push:
    branches:
      - beta
    paths:
      - "**.php"

jobs:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v4
      name: Check out Git repository
      with:
        dir: "."

    - uses: prestashop/github-action-php-lint/8.0@v2.1
      name: PHP syntax checker 8.0
      with:
        dir: "."
